@MuntersInterview.Giphy.API_HostAddress = http://localhost:5203

### Search GIFs by term
GET {{MuntersInterview.Giphy.API_HostAddress}}/api/giphy/search?term=cats
Accept: application/json

###

### Search GIFs - missing term (expect 400)
GET {{MuntersInterview.Giphy.API_HostAddress}}/api/giphy/search
Accept: application/json

###
